//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("myDatabaseModel", "FK_tb_Terminals_tb_TmlStatus", "tb_TmlStatus", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WcfAndDatabaseService.tb_TmlStatus), "tb_Terminals", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WcfAndDatabaseService.tb_Terminals), true)]
[assembly: EdmRelationshipAttribute("myDatabaseModel", "FK_tb_Warning_tb_Terminals", "tb_Terminals", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WcfAndDatabaseService.tb_Terminals), "tb_Warning", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WcfAndDatabaseService.tb_Warning), true)]

#endregion

namespace WcfAndDatabaseService
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class myDatabaseEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“myDatabaseEntities”部分中的连接字符串初始化新 myDatabaseEntities 对象。
        /// </summary>
        public myDatabaseEntities() : base("name=myDatabaseEntities", "myDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 myDatabaseEntities 对象。
        /// </summary>
        public myDatabaseEntities(string connectionString) : base(connectionString, "myDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 myDatabaseEntities 对象。
        /// </summary>
        public myDatabaseEntities(EntityConnection connection) : base(connection, "myDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tb_Terminals> tb_Terminals
        {
            get
            {
                if ((_tb_Terminals == null))
                {
                    _tb_Terminals = base.CreateObjectSet<tb_Terminals>("tb_Terminals");
                }
                return _tb_Terminals;
            }
        }
        private ObjectSet<tb_Terminals> _tb_Terminals;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tb_TmlStatus> tb_TmlStatus
        {
            get
            {
                if ((_tb_TmlStatus == null))
                {
                    _tb_TmlStatus = base.CreateObjectSet<tb_TmlStatus>("tb_TmlStatus");
                }
                return _tb_TmlStatus;
            }
        }
        private ObjectSet<tb_TmlStatus> _tb_TmlStatus;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tb_Users> tb_Users
        {
            get
            {
                if ((_tb_Users == null))
                {
                    _tb_Users = base.CreateObjectSet<tb_Users>("tb_Users");
                }
                return _tb_Users;
            }
        }
        private ObjectSet<tb_Users> _tb_Users;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tb_Warning> tb_Warning
        {
            get
            {
                if ((_tb_Warning == null))
                {
                    _tb_Warning = base.CreateObjectSet<tb_Warning>("tb_Warning");
                }
                return _tb_Warning;
            }
        }
        private ObjectSet<tb_Warning> _tb_Warning;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 tb_Terminals EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotb_Terminals(tb_Terminals tb_Terminals)
        {
            base.AddObject("tb_Terminals", tb_Terminals);
        }
    
        /// <summary>
        /// 用于向 tb_TmlStatus EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotb_TmlStatus(tb_TmlStatus tb_TmlStatus)
        {
            base.AddObject("tb_TmlStatus", tb_TmlStatus);
        }
    
        /// <summary>
        /// 用于向 tb_Users EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotb_Users(tb_Users tb_Users)
        {
            base.AddObject("tb_Users", tb_Users);
        }
    
        /// <summary>
        /// 用于向 tb_Warning EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotb_Warning(tb_Warning tb_Warning)
        {
            base.AddObject("tb_Warning", tb_Warning);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myDatabaseModel", Name="tb_Terminals")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_Terminals : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tb_Terminals 对象。
        /// </summary>
        /// <param name="tmlID">tmlID 属性的初始值。</param>
        /// <param name="phoneNumber">PhoneNumber 属性的初始值。</param>
        public static tb_Terminals Createtb_Terminals(global::System.Int32 tmlID, global::System.String phoneNumber)
        {
            tb_Terminals tb_Terminals = new tb_Terminals();
            tb_Terminals.tmlID = tmlID;
            tb_Terminals.PhoneNumber = phoneNumber;
            return tb_Terminals;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tmlID
        {
            get
            {
                return _tmlID;
            }
            set
            {
                if (_tmlID != value)
                {
                    OntmlIDChanging(value);
                    ReportPropertyChanging("tmlID");
                    _tmlID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("tmlID");
                    OntmlIDChanged();
                }
            }
        }
        private global::System.Int32 _tmlID;
        partial void OntmlIDChanging(global::System.Int32 value);
        partial void OntmlIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Longitude;
        partial void OnLongitudeChanging(Nullable<global::System.Double> value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Latitude;
        partial void OnLatitudeChanging(Nullable<global::System.Double> value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> TmlStusID
        {
            get
            {
                return _TmlStusID;
            }
            set
            {
                OnTmlStusIDChanging(value);
                ReportPropertyChanging("TmlStusID");
                _TmlStusID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TmlStusID");
                OnTmlStusIDChanged();
            }
        }
        private Nullable<global::System.Int16> _TmlStusID;
        partial void OnTmlStusIDChanging(Nullable<global::System.Int16> value);
        partial void OnTmlStusIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("myDatabaseModel", "FK_tb_Terminals_tb_TmlStatus", "tb_TmlStatus")]
        public tb_TmlStatus tb_TmlStatus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_TmlStatus>("myDatabaseModel.FK_tb_Terminals_tb_TmlStatus", "tb_TmlStatus").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_TmlStatus>("myDatabaseModel.FK_tb_Terminals_tb_TmlStatus", "tb_TmlStatus").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_TmlStatus> tb_TmlStatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_TmlStatus>("myDatabaseModel.FK_tb_Terminals_tb_TmlStatus", "tb_TmlStatus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_TmlStatus>("myDatabaseModel.FK_tb_Terminals_tb_TmlStatus", "tb_TmlStatus", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("myDatabaseModel", "FK_tb_Warning_tb_Terminals", "tb_Warning")]
        public EntityCollection<tb_Warning> tb_Warning
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_Warning>("myDatabaseModel.FK_tb_Warning_tb_Terminals", "tb_Warning");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_Warning>("myDatabaseModel.FK_tb_Warning_tb_Terminals", "tb_Warning", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myDatabaseModel", Name="tb_TmlStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_TmlStatus : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tb_TmlStatus 对象。
        /// </summary>
        /// <param name="tmlStusID">TmlStusID 属性的初始值。</param>
        /// <param name="tmlStusName">TmlStusName 属性的初始值。</param>
        public static tb_TmlStatus Createtb_TmlStatus(global::System.Int16 tmlStusID, global::System.String tmlStusName)
        {
            tb_TmlStatus tb_TmlStatus = new tb_TmlStatus();
            tb_TmlStatus.TmlStusID = tmlStusID;
            tb_TmlStatus.TmlStusName = tmlStusName;
            return tb_TmlStatus;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 TmlStusID
        {
            get
            {
                return _TmlStusID;
            }
            set
            {
                if (_TmlStusID != value)
                {
                    OnTmlStusIDChanging(value);
                    ReportPropertyChanging("TmlStusID");
                    _TmlStusID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TmlStusID");
                    OnTmlStusIDChanged();
                }
            }
        }
        private global::System.Int16 _TmlStusID;
        partial void OnTmlStusIDChanging(global::System.Int16 value);
        partial void OnTmlStusIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TmlStusName
        {
            get
            {
                return _TmlStusName;
            }
            set
            {
                OnTmlStusNameChanging(value);
                ReportPropertyChanging("TmlStusName");
                _TmlStusName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TmlStusName");
                OnTmlStusNameChanged();
            }
        }
        private global::System.String _TmlStusName;
        partial void OnTmlStusNameChanging(global::System.String value);
        partial void OnTmlStusNameChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("myDatabaseModel", "FK_tb_Terminals_tb_TmlStatus", "tb_Terminals")]
        public EntityCollection<tb_Terminals> tb_Terminals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_Terminals>("myDatabaseModel.FK_tb_Terminals_tb_TmlStatus", "tb_Terminals");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_Terminals>("myDatabaseModel.FK_tb_Terminals_tb_TmlStatus", "tb_Terminals", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myDatabaseModel", Name="tb_Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_Users : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tb_Users 对象。
        /// </summary>
        /// <param name="userID">UserID 属性的初始值。</param>
        /// <param name="loginName">LoginName 属性的初始值。</param>
        /// <param name="password">Password 属性的初始值。</param>
        public static tb_Users Createtb_Users(global::System.Int32 userID, global::System.String loginName, global::System.String password)
        {
            tb_Users tb_Users = new tb_Users();
            tb_Users.UserID = userID;
            tb_Users.LoginName = loginName;
            tb_Users.Password = password;
            return tb_Users;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoginName
        {
            get
            {
                return _LoginName;
            }
            set
            {
                OnLoginNameChanging(value);
                ReportPropertyChanging("LoginName");
                _LoginName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LoginName");
                OnLoginNameChanged();
            }
        }
        private global::System.String _LoginName;
        partial void OnLoginNameChanging(global::System.String value);
        partial void OnLoginNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NickName
        {
            get
            {
                return _NickName;
            }
            set
            {
                OnNickNameChanging(value);
                ReportPropertyChanging("NickName");
                _NickName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NickName");
                OnNickNameChanged();
            }
        }
        private global::System.String _NickName;
        partial void OnNickNameChanging(global::System.String value);
        partial void OnNickNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rank
        {
            get
            {
                return _Rank;
            }
            set
            {
                OnRankChanging(value);
                ReportPropertyChanging("Rank");
                _Rank = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Rank");
                OnRankChanged();
            }
        }
        private global::System.String _Rank;
        partial void OnRankChanging(global::System.String value);
        partial void OnRankChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PopedomID
        {
            get
            {
                return _PopedomID;
            }
            set
            {
                OnPopedomIDChanging(value);
                ReportPropertyChanging("PopedomID");
                _PopedomID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PopedomID");
                OnPopedomIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PopedomID;
        partial void OnPopedomIDChanging(Nullable<global::System.Int32> value);
        partial void OnPopedomIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myDatabaseModel", Name="tb_Warning")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_Warning : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tb_Warning 对象。
        /// </summary>
        /// <param name="wrnID">WrnID 属性的初始值。</param>
        /// <param name="reportTime">ReportTime 属性的初始值。</param>
        /// <param name="tmlID">tmlID 属性的初始值。</param>
        public static tb_Warning Createtb_Warning(global::System.Int32 wrnID, global::System.DateTime reportTime, global::System.Int32 tmlID)
        {
            tb_Warning tb_Warning = new tb_Warning();
            tb_Warning.WrnID = wrnID;
            tb_Warning.ReportTime = reportTime;
            tb_Warning.tmlID = tmlID;
            return tb_Warning;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WrnID
        {
            get
            {
                return _WrnID;
            }
            set
            {
                if (_WrnID != value)
                {
                    OnWrnIDChanging(value);
                    ReportPropertyChanging("WrnID");
                    _WrnID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WrnID");
                    OnWrnIDChanged();
                }
            }
        }
        private global::System.Int32 _WrnID;
        partial void OnWrnIDChanging(global::System.Int32 value);
        partial void OnWrnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ReportTime
        {
            get
            {
                return _ReportTime;
            }
            set
            {
                OnReportTimeChanging(value);
                ReportPropertyChanging("ReportTime");
                _ReportTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReportTime");
                OnReportTimeChanged();
            }
        }
        private global::System.DateTime _ReportTime;
        partial void OnReportTimeChanging(global::System.DateTime value);
        partial void OnReportTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> HandleTime
        {
            get
            {
                return _HandleTime;
            }
            set
            {
                OnHandleTimeChanging(value);
                ReportPropertyChanging("HandleTime");
                _HandleTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HandleTime");
                OnHandleTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _HandleTime;
        partial void OnHandleTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnHandleTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tmlID
        {
            get
            {
                return _tmlID;
            }
            set
            {
                OntmlIDChanging(value);
                ReportPropertyChanging("tmlID");
                _tmlID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tmlID");
                OntmlIDChanged();
            }
        }
        private global::System.Int32 _tmlID;
        partial void OntmlIDChanging(global::System.Int32 value);
        partial void OntmlIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HandleResult
        {
            get
            {
                return _HandleResult;
            }
            set
            {
                OnHandleResultChanging(value);
                ReportPropertyChanging("HandleResult");
                _HandleResult = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HandleResult");
                OnHandleResultChanged();
            }
        }
        private global::System.String _HandleResult;
        partial void OnHandleResultChanging(global::System.String value);
        partial void OnHandleResultChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("myDatabaseModel", "FK_tb_Warning_tb_Terminals", "tb_Terminals")]
        public tb_Terminals tb_Terminals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_Terminals>("myDatabaseModel.FK_tb_Warning_tb_Terminals", "tb_Terminals").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_Terminals>("myDatabaseModel.FK_tb_Warning_tb_Terminals", "tb_Terminals").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_Terminals> tb_TerminalsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_Terminals>("myDatabaseModel.FK_tb_Warning_tb_Terminals", "tb_Terminals");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_Terminals>("myDatabaseModel.FK_tb_Warning_tb_Terminals", "tb_Terminals", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
